from setuptools import setup, find_packages

setup(
    name="vehicle-registration-ai",
    version="1.0.0",
    description="AI-powered Vehicle Registration Analysis System with Multi-Agent Architecture",
    author="Nithin",
    author_email="nithin@example.com",
    packages=find_packages(),
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.0", 
        "sqlalchemy>=2.0.0",
        "llama-index>=0.9.0",
        "llama-index-llms-openai>=0.1.0",
        "llama-index-embeddings-openai>=0.1.0",
        "langgraph>=0.0.60",
        "langchain>=0.1.0",
        "langchain-openai>=0.1.0",
        "langchain-core>=0.1.0",
        "openai>=1.0.0",
        "python-dotenv>=1.0.0",
        "loguru>=0.7.0",
        "rich>=13.0.0",
        "jupyter>=1.0.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.15.0",
    ],
    python_requires=">=3.9",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    entry_points={
        "console_scripts": [
            "vehicle-ai=src.main:main",
        ],
    },
)